
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
// import { SessionProvider } from "next-auth/react";

import { Providers } from "@/app/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MindMosaic",
  description: "Generated by create next app",
  icons: {
    icon: '/assets/MM.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={inter.className}>

      <SpeedInsights />
      {/* <Providers> */}
        
        {/* <SessionProvider> */}
        <Header />
        {children}
        <Footer />
        {/* // </SessionProvider> */}
       
        {/* </Providers> */}
        <Analytics />
      </body>
    </html>

  );
}
